### ISSUE TITLE
An error occurred while processing a request in MyMQTTSkill.

### ISSUE THREAD

**Issue by arturmaj** [jamiehoward430/mycroft-mymqtt#2]
I am running picroft 0.85. My paho installation is working well. I tested anonymous and authenticated connections. In both cases I am getting: An error occurred while processing a request in MyMQTTSkill. How can I debug this?

**Comment by jamiehoward430** [comment]
Hi,

Try changing lines 36, 37 and 38 in `__init__.py` from

```
cmd_name = message.metadata.get("CommandKeyword")
mdl_name = message.metadata.get("ModuleKeyword")
act_name = message.metadata.get("ActionKeyword")
```

to

```
cmd_name = message.data.get("CommandKeyword")
mdl_name = message.data.get("ModuleKeyword")
act_name = message.data.get("ActionKeyword")
```

**Comment by arturmaj** [comment]
Hello,
Thanks for the plugin. No change.

**Comment by jamiehoward430** [comment]
are you using authentication?

**Comment by arturmaj** [comment]
I am testing both anonymous and with authentication.
I also tried cmd_name, mdl_name and act_name as constant strings but the error still occurs.

**Comment by jamiehoward430** [comment]
Hi

Remove the quotes around the port number in the config file, 
for no auth
```
  `"MyMQTTSkill":` {
    "protocol": "mqtt",
    "mqtt-host": "192.168.0.200",
    "mqtt-port": 1883,
    "mqtt-auth": "no",
    "mqtt-user": "",
    "mqtt-pass": ""
  }
```

with auth

```
  "MyMQTTSkill": {
    "protocol": "mqtt",
    "mqtt-host": "192.168.0.200",
    "mqtt-port": 1883,
    "mqtt-auth": "yes",
    "mqtt-user": "user",
    "mqtt-pass": "pass"
  }
```

**Comment by arturmaj** [comment]
Thank you. It worked:
1. data instead metadata
2. removed quotes from port.
